const surahList = [
  {
    englishName: "1. Al-Faatiha (The Opening)",
    e: "7 Ayahs",
    name: "سُورَةُ ٱلْفَاتِحَةِ",
    e: "٧ آيات",
  },

  {
    englishName: "2. Al-Baqara (The Cow)",
    e: "286 Ayahs",
    name: "سُورَةُ البَقَرَةِ",
    e: "٢٨٦ آيات",
  },

  {
    englishName: "3. Aal-i-Imraan (The Family of Imraan)",
    e: "200 Ayahs",
    name: "سُورَةُ آلِ عِمۡرَانَ",
    e: "٢٠٠ آيات",
  },

  {
    englishName: "4. An-Nisaa (The Women)",
    e: "176 Ayahs",
    name: "سُورَةُ النِّسَاءِ",
    e: "١٧٦ آيات",
  },

  {
    englishName: "5. Al-Maaida (The Table)",
    e: "120 Ayahs",
    name: "سُورَةُ المَائـِدَةِ",
    e: "١٢٠ آيات",
  },

  {
    englishName: "6. Al-An'aam (The Cattle)",
    e: "165 Ayahs",
    name: "سُورَةُ الأَنۡعَامِ",
    e: "١٦٥ آيات",
  },

  {
    englishName: "7. Al-A'raaf (The Heights)",
    e: "206 Ayahs",
    name: "سُورَةُ الأَعۡرَافِ",
    e: "٢٠٦ آيات",
  },

  {
    englishName: "8. Al-Anfaal (The Spoils of War)",
    e: "75 Ayahs",
    name: "سُورَةُ الأَنفَالِ",
    e: "٧٥ آيات",
  },

  {
    englishName: "9. At-Tawba (The Repentance)",
    e: "129 Ayahs",
    name: "سُورَةُ التَّوۡبَةِ",
    e: "١٢٩ آيات",
  },

  {
    englishName: "10. Yunus (Jonas)",
    e: "109 Ayahs",
    name: "سُورَةُ يُونُسَ",
    e: "١٠٩ آيات",
  },

  {
    englishName: "11. Hud (Hud)",
    e: "123 Ayahs",
    name: "سُورَةُ هُودٍ",
    e: "١٢٣ آيات",
  },

  {
    englishName: "12. Yusuf (Joseph)",
    e: "111 Ayahs",
    name: "سُورَةُ يُوسُفَ",
    e: "١١١ آيات",
  },
];
/*
e: "",
e: "13. Ar-Ra'd (The Thunder)",
e: "43 Ayahs",
e: "",
e: "سُورَةُ الرَّعۡدِ",
e: "٤٣ آيات",
e: "",
e: "14. Ibrahim (Abraham)",
e: "52 Ayahs",
e: "",
e: "سُورَةُ إِبۡرَاهِيمَ",
e: "٥٢ آيات",
e: "",
e: "15. Al-Hijr (The Rock)",
e: "99 Ayahs",
e: "",
e: "سُورَةُ الحِجۡرِ",
e: "٩٩ آيات",
e: "",
e: "16. An-Nahl (The Bee)",
e: "128 Ayahs",
e: "",
e: "سُورَةُ النَّحۡلِ",
e: "١٢٨ آيات",
e: "",
e: "17. Al-Israa (The Night Journey)",
e: "111 Ayahs",
e: "",
e: "سُورَةُ الإِسۡرَاءِ",
e: "١١١ آيات",
e: "",
e: "18. Al-Kahf (The Cave)",
e: "110 Ayahs",
e: "",
e: "سُورَةُ الكَهۡفِ",
e: "١١٠ آيات",
e: "",
e: "19. Maryam (Mary)",
e: "98 Ayahs",
e: "",
e: "سُورَةُ مَرۡيَمَ",
e: "٩٨ آيات",
e: "",
e: "20. Taa-Haa (Taa-Haa)",
e: "135 Ayahs",
e: "",
e: "سُورَةُ طه",
e: "١٣٥ آيات",
e: "",
e: "21. Al-Anbiyaa (The Prophets)",
e: "112 Ayahs",
e: "",
e: "سُورَةُ الأَنبِيَاءِ",
e: "١١٢ آيات",
e: "",
e: "22. Al-Hajj (The Pilgrimage)",
e: "78 Ayahs",
e: "",
e: "سُورَةُ الحَجِّ",
e: "٧٨ آيات",
e: "",
e: "23. Al-Muminoon (The Believers)",
e: "118 Ayahs",
e: "",
e: "سُورَةُ المُؤۡمِنُونَ",
e: "١١٨ آيات",
e: "",
e: "24. An-Noor (The Light)",
e: "64 Ayahs",
e: "",
e: "سُورَةُ النُّورِ",
e: "٦٤ آيات",
e: "",
e: "25. Al-Furqaan (The Criterion)",
e: "77 Ayahs",
e: "",
e: "سُورَةُ الفُرۡقَانِ",
e: "٧٧ آيات",
e: "",
e: "26. Ash-Shu'araa (The Poets)",
e: "227 Ayahs",
e: "",
e: "سُورَةُ الشُّعَرَاءِ",
e: "٢٢٧ آيات",
e: "",
e: "27. An-Naml (The Ant)",
e: "93 Ayahs",
e: "",
e: "سُورَةُ النَّمۡلِ",
e: "٩٣ آيات",
e: "",
e: "28. Al-Qasas (The Stories)",
e: "88 Ayahs",
e: "",
e: "سُورَةُ القَصَصِ",
e: "٨٨ آيات",
e: "",
e: "29. Al-Ankaboot (The Spider)",
e: "69 Ayahs",
e: "",
e: "سُورَةُ العَنكَبُوتِ",
e: "٦٩ آيات",
e: "",
e: "30. Ar-Room (The Romans)",
e: "60 Ayahs",
e: "",
e: "سُورَةُ الرُّومِ",
e: "٦٠ آيات",
e: "",
e: "31. Luqman (Luqman)",
e: "34 Ayahs",
e: "",
e: "سُورَةُ لُقۡمَانَ",
e: "٣٤ آيات",
e: "",
e: "32. As-Sajda (The Prostration)",
e: "30 Ayahs",
e: "",
e: "سُورَةُ السَّجۡدَةِ",
e: "٣٠ آيات",
e: "",
e: "33. Al-Ahzaab (The Clans)",
e: "73 Ayahs",
e: "",
e: "سُورَةُ الأَحۡزَابِ",
e: "٧٣ آيات",
e: "",
e: "34. Saba (Sheba)",
e: "54 Ayahs",
e: "",
e: "سُورَةُ سَبَإٍ",
e: "٥٤ آيات",
e: "",
e: "35. Faatir (The Originator)",
e: "45 Ayahs",
e: "",
e: "سُورَةُ فَاطِرٍ",
e: "٤٥ آيات",
e: "",
e: "36. Yaseen (Yaseen)",
e: "83 Ayahs",
e: "",
e: "سُورَةُ يسٓ",
e: "٨٣ آيات",
e: "",
e: "37. As-Saaffaat (Those drawn up in Ranks)",
e: "182 Ayahs",
e: "",
e: "سُورَةُ الصَّافَّاتِ",
e: "١٨٢ آيات",
e: "",
e: "38. Saad (The letter Saad)",
e: "88 Ayahs",
e: "",
e: "سُورَةُ صٓ",
e: "٨٨ آيات",
e: "",
e: "39. Az-Zumar (The Groups)",
e: "75 Ayahs",
e: "",
e: "سُورَةُ الزُّمَرِ",
e: "٧٥ آيات",
e: "",
e: "40. Ghafir (The Forgiver)",
e: "85 Ayahs",
e: "",
e: "سُورَةُ غَافِرٍ",
e: "٨٥ آيات",
e: "",
e: "41. Fussilat (Explained in detail)",
e: "54 Ayahs",
e: "",
e: "سُورَةُ فُصِّلَتۡ",
e: "٥٤ آيات",
e: "",
e: "42. Ash-Shura (Consultation)",
e: "53 Ayahs",
e: "",
e: "سُورَةُ الشُّورَىٰ",
e: "٥٣ آيات",
e: "",
e: "43. Az-Zukhruf (OrenglishNaments of gold)",
e: "89 Ayahs",
e: "",
e: "سُورَةُ الزُّخۡرُفِ",
e: "٨٩ آيات",
e: "",
e: "44. Ad-Dukhaan (The Smoke)",
e: "59 Ayahs",
e: "",
e: "سُورَةُ الدُّخَانِ",
e: "٥٩ آيات",
e: "",
e: "45. Al-Jaathiya (Crouching)",
e: "37 Ayahs",
e: "",
e: "سُورَةُ الجَاثِيَةِ",
e: "٣٧ آيات",
e: "",
e: "46. Al-Ahqaf (The Dunes)",
e: "35 Ayahs",
e: "",
e: "سُورَةُ الأَحۡقَافِ",
e: "٣٥ آيات",
e: "",
e: "47. Muhammad (Muhammad)",
e: "38 Ayahs",
e: "",
e: "سُورَةُ مُحَمَّدٍ",
e: "٣٨ آيات",
e: "",
e: "48. Al-Fath (The Victory)",
e: "29 Ayahs",
e: "",
e: "سُورَةُ الفَتۡحِ",
e: "٢٩ آيات",
e: "",
e: "49. Al-Hujuraat (The Inner Apartments)",
e: "18 Ayahs",
e: "",
e: "سُورَةُ الحُجُرَاتِ",
e: "١٨ آيات",
e: "",
e: "50. Qaaf (The letter Qaaf)",
e: "45 Ayahs",
e: "",
e: "سُورَةُ قٓ",
e: "٤٥ آيات",
e: "",
e: "51. Adh-Dhaariyat (The Winnowing Winds)",
e: "60 Ayahs",
e: "",
e: "سُورَةُ الذَّارِيَاتِ",
e: "٦٠ آيات",
e: "",
e: "52. At-Tur (The Mount)",
e: "49 Ayahs",
e: "",
e: "سُورَةُ الطُّورِ",
e: "٤٩ آيات",
e: "",
e: "53. An-Najm (The Star)",
e: "62 Ayahs",
e: "",
e: "سُورَةُ النَّجۡمِ",
e: "٦٢ آيات",
e: "",
e: "54. Al-Qamar (The Moon)",
e: "55 Ayahs",
e: "",
e: "سُورَةُ القَمَرِ",
e: "٥٥ آيات",
e: "",
e: "55. Ar-Rahmaan (The Beneficent)",
e: "78 Ayahs",
e: "",
e: "سُورَةُ الرَّحۡمَٰن",
e: "٧٨ آيات",
e: "",
e: "56. Al-Waaqia (The Inevitable)",
e: "96 Ayahs",
e: "",
e: "سُورَةُ الوَاقِعَةِ",
e: "٩٦ آيات",
e: "",
e: "57. Al-Hadid (The Iron)",
e: "29 Ayahs",
e: "",
e: "سُورَةُ الحَدِيدِ",
e: "٢٩ آيات",
e: "",
e: "58. Al-Mujaadila (The Pleading Woman)",
e: "22 Ayahs",
e: "",
e: "سُورَةُ المُجَادلَةِ",
e: "٢٢ آيات",
e: "",
e: "59. Al-Hashr (The Exile)",
e: "24 Ayahs",
e: "",
e: "سُورَةُ الحَشۡرِ",
e: "٢٤ آيات",
e: "",
e: "60. Al-Mumtahana (She that is to be examined)",
e: "13 Ayahs",
e: "",
e: "سُورَةُ المُمۡتَحنَةِ",
e: "١٣ آيات",
e: "",
e: "61. As-Saff (The Ranks)",
e: "14 Ayahs",
e: "",
e: "سُورَةُ الصَّفِّ",
e: "١٤ آيات",
e: "",
e: "62. Al-Jumu'a (Friday)",
e: "11 Ayahs",
e: "",
e: "سُورَةُ الجُمُعَةِ",
e: "١١ آيات",
e: "",
e: "63. Al-Munaafiqoon (The Hypocrites)",
e: "11 Ayahs",
e: "",
e: "سُورَةُ المُنَافِقُونَ",
e: "١١ آيات",
e: "",
e: "64. At-Taghaabun (Mutual Disillusion)",
e: "18 Ayahs",
e: "",
e: "سُورَةُ التَّغَابُنِ",
e: "١٨ آيات",
e: "",
e: "65. At-Talaaq (Divorce)",
e: "12 Ayahs",
e: "",
e: "سُورَةُ الطَّلَاقِ",
e: "١٢ آيات",
e: "",
e: "66. At-Tahrim (The Prohibition)",
e: "12 Ayahs",
e: "",
e: "سُورَةُ التَّحۡرِيمِ",
e: "١٢ آيات",
e: "",
e: "67. Al-Mulk (The Sovereignty)",
e: "30 Ayahs",
e: "",
e: "سُورَةُ المُلۡكِ",
e: "٣٠ آيات",
e: "",
e: "68. Al-Qalam (The Pen)",
e: "52 Ayahs",
e: "",
e: "سُورَةُ القَلَمِ",
e: "٥٢ آيات",
e: "",
e: "69. Al-Haaqqa (The Reality)",
e: "52 Ayahs",
e: "",
e: "سُورَةُ الحَاقَّةِ",
e: "٥٢ آيات",
e: "",
e: "70. Al-Ma'aarij (The Ascending Stairways)",
e: "44 Ayahs",
e: "",
e: "سُورَةُ المَعَارِجِ",
e: "٤٤ آيات",
e: "",
e: "71. Nooh (Noah)",
e: "28 Ayahs",
e: "",
e: "سُورَةُ نُوحٍ",
e: "٢٨ آيات",
e: "",
e: "72. Al-Jinn (The Jinn)",
e: "28 Ayahs",
e: "",
e: "سُورَةُ الجِنِّ",
e: "٢٨ آيات",
e: "",
e: "73. Al-Muzzammil (The Enshrouded One)",
e: "20 Ayahs",
e: "",
e: "سُورَةُ المُزَّمِّلِ",
e: "٢٠ آيات",
e: "",
e: "74. Al-Muddaththir (The Cloaked One)",
e: "56 Ayahs",
e: "",
e: "سُورَةُ المُدَّثِّرِ",
e: "٥٦ آيات",
e: "",
e: "75. Al-Qiyaama (The Resurrection)",
e: "40 Ayahs",
e: "",
e: "سُورَةُ القِيَامَةِ",
e: "٤٠ آيات",
e: "",
e: "76. Al-Insaan (Man)",
e: "31 Ayahs",
e: "",
e: "سُورَةُ الإِنسَانِ",
e: "٣١ آيات",
e: "",
e: "77. Al-Mursalaat (The Emissaries)",
e: "50 Ayahs",
e: "",
e: "سُورَةُ المُرۡسَلَاتِ",
e: "٥٠ آيات",
e: "",
e: "78. An-Naba (The Announcement)",
e: "40 Ayahs",
e: "",
e: "سُورَةُ النَّبَإِ",
e: "٤٠ آيات",
e: "",
e: "79. An-Naazi'aat (Those who drag forth)",
e: "46 Ayahs",
e: "",
e: "سُورَةُ النَّازِعَاتِ",
e: "٤٦ آيات",
e: "",
e: "80. Abasa (He frowned)",
e: "42 Ayahs",
e: "",
e: "سُورَةُ عَبَسَ",
e: "٤٢ آيات",
e: "",
e: "81. At-Takwir (The Overthrowing)",
e: "29 Ayahs",
e: "",
e: "سُورَةُ التَّكۡوِيرِ",
e: "٢٩ آيات",
e: "",
e: "82. Al-Infitaar (The Cleaving)",
e: "19 Ayahs",
e: "",
e: "سُورَةُ الانفِطَارِ",
e: "١٩ آيات",
e: "",
e: "83. Al-Mutaffifin (Defrauding)",
e: "36 Ayahs",
e: "",
e: "سُورَةُ المُطَفِّفِينَ",
e: "٣٦ آيات",
e: "",
e: "84. Al-Inshiqaaq (The Splitting Open)",
e: "25 Ayahs",
e: "",
e: "سُورَةُ الانشِقَاقِ",
e: "٢٥ آيات",
e: "",
e: "85. Al-Burooj (The Constellations)",
e: "22 Ayahs",
e: "",
e: "سُورَةُ البُرُوجِ",
e: "٢٢ آيات",
e: "",
e: "86. At-Taariq (The Morning Star)",
e: "17 Ayahs",
e: "",
e: "سُورَةُ الطَّارِقِ",
e: "١٧ آيات",
e: "",
e: "87. Al-A'laa (The Most High)",
e: "19 Ayahs",
e: "",
e: "سُورَةُ الأَعۡلَىٰ",
e: "١٩ آيات",
e: "",
e: "88. Al-Ghaashiya (The Overwhelming)",
e: "26 Ayahs",
e: "",
e: "سُورَةُ الغَاشِيَةِ",
e: "٢٦ آيات",
e: "",
e: "89. Al-Fajr (The Dawn)",
e: "30 Ayahs",
e: "",
e: "سُورَةُ الفَجۡرِ",
e: "٣٠ آيات",
e: "",
e: "90. Al-Balad (The City)",
e: "20 Ayahs",
e: "",
e: "سُورَةُ البَلَدِ",
e: "٢٠ آيات",
e: "",
e: "91. Ash-Shams (The Sun)",
e: "15 Ayahs",
e: "",
e: "سُورَةُ الشَّمۡسِ",
e: "١٥ آيات",
e: "",
e: "92. Al-Lail (The Night)",
e: "21 Ayahs",
e: "",
e: "سُورَةُ اللَّيۡلِ",
e: "٢١ آيات",
e: "",
e: "93. Ad-Dhuhaa (The Morning Hours)",
e: "11 Ayahs",
e: "",
e: "سُورَةُ الضُّحَىٰ",
e: "١١ آيات",
e: "",
e: "94. Ash-Sharh (The Consolation)",
e: "8 Ayahs",
e: "",
e: "سُورَةُ الشَّرۡحِ",
e: "٨ آيات",
e: "",
e: "95. At-Tin (The Fig)",
e: "8 Ayahs",
e: "",
e: "سُورَةُ التِّينِ",
e: "٨ آيات",
e: "",
e: "96. Al-Alaq (The Clot)",
e: "19 Ayahs",
e: "",
e: "سُورَةُ العَلَقِ",
e: "١٩ آيات",
e: "",
e: "97. Al-Qadr (The Power, Fate)",
e: "5 Ayahs",
e: "",
e: "سُورَةُ القَدۡرِ",
e: "٥ آيات",
e: "",
e: "98. Al-Bayyina (The Evidence)",
e: "8 Ayahs",
e: "",
e: "سُورَةُ البَيِّنَةِ",
e: "٨ آيات",
e: "",
e: "99. Az-Zalzala (The Earthquake)",
e: "8 Ayahs",
e: "",
e: "سُورَةُ الزَّلۡزَلَةِ",
e: "٨ آيات",
e: "",
e: "100. Al-Aadiyaat (The Chargers)",
e: "11 Ayahs",
e: "",
e: "سُورَةُ العَادِيَاتِ",
e: "١١ آيات",
e: "",
e: "101. Al-Qaari'a (The Calamity)",
e: "11 Ayahs",
e: "",
e: "سُورَةُ القَارِعَةِ",
e: "١١ آيات",
e: "",
e: "102. At-Takaathur (Competition)",
e: "8 Ayahs",
e: "",
e: "سُورَةُ التَّكَاثُرِ",
e: "٨ آيات",
e: "",
e: "103. Al-Asr (The Declining Day, Epoch)",
e: "3 Ayahs",
e: "",
e: "سُورَةُ العَصۡرِ",
e: "٣ آيات",
e: "",
e: "104. Al-Humaza (The Traducer)",
e: "9 Ayahs",
e: "",
e: "سُورَةُ الهُمَزَةِ",
e: "٩ آيات",
e: "",
e: "105. Al-Fil (The Elephant)",
e: "5 Ayahs",
e: "",
e: "سُورَةُ الفِيلِ",
e: "٥ آيات",
e: "",
e: "106. Quraish (Quraysh)",
e: "4 Ayahs",
e: "",
e: "سُورَةُ قُرَيۡشٍ",
e: "٤ آيات",
e: "",
e: "107. Al-Maa'un (Almsgiving)",
e: "7 Ayahs",
e: "",
e: "سُورَةُ المَاعُونِ",
e: "٧ آيات",
e: "",
e: "108. Al-Kawthar (Abundance)",
e: "3 Ayahs",
e: "",
e: "سُورَةُ الكَوۡثَرِ",
e: "٣ آيات",
e: "",
e: "109. Al-Kaafiroon (The Disbelievers)",
e: "6 Ayahs",
e: "",
e: "سُورَةُ الكَافِرُونَ",
e: "٦ آيات",
e: "",
e: "110. An-Nasr (Divine Support)",
e: "3 Ayahs",
e: "",
e: "سُورَةُ النَّصۡرِ",
e: "٣ آيات",
e: "",
e: "111. Al-Masad (The Palm Fibre)",
e: "5 Ayahs",
e: "",
e: "سُورَةُ المَسَدِ",
e: "٥ آيات",
e: "",
e: "112. Al-Ikhlaas (Sincerity)",
e: "4 Ayahs",
e: "",
e: "سُورَةُ الإِخۡلَاصِ",
e: "٤ آيات",
e: "",
e: "113. Al-Falaq (The Dawn)",
e: "5 Ayahs",
e: "",
e: "سُورَةُ الفَلَقِ",
e: "٥ آيات",
e: "",
e: "114. An-Naas (Mankind)",
e: "6 Ayahs",
e: "",
e: "سُورَةُ النَّاسِ",
e: "٦ آيات",
]
*/
export default surahList;
