import { useState } from "react";
import axios from "axios";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Jumbotron from "../components/Jumbotron";
import Header from "../components/Header";
import SurahGrid from "../components/SurahGrid";

export default function Home({surahs}) {
  const [surah, setSurah] = useState(1)
  const [spinner, setSpinner] = useState(false)
  const [readingMode, setReadingMode] = useState(false);
  const [query, setQuery] = useState("1");

  const sendQuery = () => {
    setSpinner(true);
    axios
      .get(baseURL + query)
      .then((res) => {
        setSurah(res.data);
        setSpinner(false);
      })
      .catch((err) => {
        alert(err + ": Nomor surah harus berupa angka 1-114");
      });
  };

  const handleForm = (e) => {
    e.preventDefault();
    sendQuery();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Alfurqan - Read your Quran</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header readingMode={readingMode} setReadingMode={setReadingMode} />

      <Jumbotron handleForm={handleForm} handleQuery={setQuery} />
      <SurahGrid data={surahs.data}/>
    </div>
  );
}

export async function getStaticProps(){
  const res = await fetch('http://api.alquran.cloud/v1/surah')
  const surahs = await res.json();
  return {
      props:{
          surahs
      }
  }
}